### ISSUE TITLE
Uncaught Error: Login authentication failed

### ISSUE THREAD

**Issue by fransiti** [h3imdall/ftp-remote-edit#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: elementary OS
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.5.2

### Stack Trace

Uncaught Error: Login authentication failed

```
At events.js:160

Error: Login authentication failed
    at makeError (/packages/ftp-remote-edit/node_modules/ftp/lib/connection.js:1067:13)
    at /packages/ftp-remote-edit/node_modules/ftp/lib/connection.js:113:25)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/ftp-remote-edit/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/ftp-remote-edit/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -1:33.2.0 tabs:close-all-tabs (input.hidden-input)
     -1:28.1.0 ftp-remote-edit:closePanel (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-one-dark-syntax.theme-atom-material-ui.has-custom-icons)
     -1:23.2.0 ftp-remote-edit:editconfiguration (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-one-dark-syntax.theme-atom-material-ui.has-custom-icons)
     -1:16.9.0 core:confirm (input.hidden-input)
  5x -0:50.8.0 core:backspace (input.hidden-input)
     -0:28.9.0 ftp-remote-edit:toggle (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-one-dark-syntax.theme-atom-material-ui.has-custom-icons)
     -0:24 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.3.0 
atom-angular-material-snippets 1.3.0 
atom-bootstrap3 1.2.12 
atom-fontawesome 0.4.0 
atom-material-ui 1.3.9 
font-awesome-snippetset 0.0.6 
fonts 2.0.0 
ftp-remote-edit 0.5.2 
seti-icons 1.4.3 
```

**Comment by h3imdall** [comment]
I added user notifications for errors and when a file is successfully saved to the server. There should be no uncaught error.
