### ISSUE TITLE
Uncaught ReferenceError: reject is not defined

### ISSUE THREAD

**Issue by BWPanda** [h3imdall/ftp-remote-edit#107]
When using Atom with this package, if I leave it too long between actions (e.g. go make a coffee), when I come back and try to save a file or open a new one, this error appears. If I'm constantly using Atom then this isn't an issue. It only happens when I leave it for a while (say, 5 mins).
If I leave it longer still (15 mins or so), then nothing saves or opens (just the little spinning loading icon next to files) and no errors appear. I have to close and re-open Atom.

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Linux Mint
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.2

### Stack Trace

Uncaught ReferenceError: reject is not defined

```
At /[HOME_DIR]/.atom/packages/ftp-remote-edit/lib/connectors/sftp.js:30

ReferenceError: reject is not defined
    at /packages/ftp-remote-edit/lib/connectors/sftp.js:30:7)
    at emitOne (events.js:96:13)
    at SftpClient.emit (events.js:188:7)
    at Client.client.on.on (/packages/ftp-remote-edit/lib/connectors/ssh2-sftp-client.js:330:20)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at /packages/ftp-remote-edit/node_modules/ssh2/lib/client.js:215:10)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
ftp-remote-edit 0.12.2 
unsaved-changes 0.1.0 
```

Please let me know if I need to provide any further info to help debug this. If so, just let me know how/what to provide. Thanks!

**Comment by BWPanda** [comment]
For reference, in case others are interested: https://github.com/h3imdall/ftp-remote-edit/commit/6159e782ace8a20a6935b9208d4bea4f27240e2f
