### ISSUE TITLE
Uncaught SyntaxError: Unexpected token / in JSON at position 0

### ISSUE THREAD

**Issue by ercellyildiz** [h3imdall/ftp-remote-edit#110]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Deepin 15.4.1
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.3

### Stack Trace

Uncaught SyntaxError: Unexpected token / in JSON at position 0

```
At file:///usr/share/atom/resources/app/static/index.html:1

SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at _TreeView.loadServers (/packages/ftp-remote-edit/lib/views/tree-view.js:247:27)
    at FtpRemoteEdit.toggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:161:21)
    at HTMLElement.ftpRemoteEditToggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:41:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:21 ftp-remote-edit:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:18.1.0 core:confirm (input.hidden-input)
     -0:12 ftp-remote-edit:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
ftp-remote-edit 0.12.3 
```

**Comment by cschindl** [comment]
Hi @ercellyildiz ,

the error has already been reported in issue #44 and a solution is being worked on.
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
Can you reproduce the error?
Did you start with a fresh new installaltion of the plugin?
Can you add new servers?
Do you see the tree view when toggle with ctrl + space?

**Comment by ercellyildiz** [comment]
Hi @cschindl 
I got the problem one by one. Thank you for your interest. :)

**Comment by cschindl** [comment]
Hi @ercellyildiz,
 
we have tried to solve the problem for a long time, but could never reproduce the error. Apparently the error occurs only by a small number of users. Unfortunately most users report only the error, but do not answer our questions. So it would be great if you could help us find the error. Can you please answer the questions?

**Comment by cschindl** [comment]
@ercellyildiz Please answer in  in issue #44.
