### ISSUE TITLE
Uncaught SyntaxError: Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by antlans** [h3imdall/ftp-remote-edit#113]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.3

### Stack Trace

Uncaught SyntaxError: Unexpected token I in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html:1

SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at ConfigurationView.loadConfig (/packages/ftp-remote-edit/lib/views/configuration-view.js:416:26)
    at ConfigurationView.reload (/packages/ftp-remote-edit/lib/views/configuration-view.js:456:31)
    at FtpRemoteEdit.editServers (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:191:28)
    at HTMLElement.ftpRemoteEditEditServers (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:42:50)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:22.6.0 ftp-remote-edit:toggle (input.hidden-input)
     -0:18.8.0 core:confirm (input.hidden-input)
     -0:09.3.0 ftp-remote-edit:edit-servers (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.2.5 
ftp-remote-edit 0.12.3 
```

**Comment by cschindl** [comment]
Hi @antlans ,

the error has already been reported in issue #44 and a solution is being worked on.
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
Can you reproduce the error?
Did you start with a fresh new installaltion of the plugin?
Can you add new servers?
Do you see the tree view when toggle with ctrl + space?
