### ISSUE TITLE
Uncaught SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by cukabeka** [h3imdall/ftp-remote-edit#115]
[Enter steps to reproduce:]

1. Enter Password on "enter" dialog
2. wait..

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.3

### Stack Trace

Uncaught SyntaxError: Unexpected token u in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html:1

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at ConfigurationView.loadConfig (/packages/ftp-remote-edit/lib/views/configuration-view.js:416:26)
    at ConfigurationView.reload (/packages/ftp-remote-edit/lib/views/configuration-view.js:456:31)
    at FtpRemoteEdit.editServers (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:191:28)
    at HTMLElement.ftpRemoteEditEditServers (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:42:50)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:24 ftp-remote-edit:toggle (input.hidden-input)
     -0:16.9.0 core:confirm (input.hidden-input)
     -0:09.9.0 ftp-remote-edit:edit-servers (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-autocomplete-php 0.25.6 
atom-ide-ui 0.4.0 
autocomplete-php 0.3.7 
editor-stats 0.17.0 
ftp-remote-edit 0.12.3 
ide-haskell 2.1.1 
linter 2.2.0 
linter-php 1.5.1 
linter-scss-lint 3.1.1 
remote-edit 1.9.0 
Remote-FTP 1.1.3 
remote-sync 4.1.5 
```

**Comment by cschindl** [comment]
Hi @cukabeka ,

the error has already been reported in issue #44 and a solution is being worked on.
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
Can you reproduce the error?
Did you start with a fresh new installaltion of the plugin?
Can you add new servers?
Do you see the tree view when toggle with ctrl + space?

**Comment by Sofianio** [comment]
Q: When does the error occur?
A: In a special situation (Described below)
Q: Do you use multiple instances of atom at the same time?
A: I use 2 windows
Q: Can you reproduce the error?
A: yes, i just did
Q: Did you start with a fresh new installaltion of the plugin?
A: no, but i have an updated version 0.12.3
Q: Can you add new servers?, Do you see the tree view when toggle with ctrl + space?
A: i can't see the tree view (in the 2nd window where the bug happened) ctrl+space throws the error popup

Special situation:
- I open 2 windows for 2 projects
- 1st window: I hit ctrl+space, I enter password "aaa", I get the tree view
- 2nd window:  I hit ctrl+space, I enter password "bbb", I get the error popup

**Comment by igun997** [comment]
in my case that problem show if password ftp-remote not correct after pressed ctrl + space will show a dialog password, if that password wrong , that error show

**Comment by cschindl** [comment]
Please answer in issue #44
