### ISSUE TITLE
Uncaught SyntaxError: Unexpected token @ in JSON at position 1

### ISSUE THREAD

**Issue by andfra1** [h3imdall/ftp-remote-edit#121]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.3

### Stack Trace

Uncaught SyntaxError: Unexpected token @ in JSON at position 1

```
At file:///E:/ATOM-portable/Atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token @ in JSON at position 1
    at JSON.parse (<anonymous>)
    at _TreeView.loadServers (/packages/ftp-remote-edit/lib/views/tree-view.js:247:27)
    at FtpRemoteEdit.toggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:161:21)
    at HTMLElement.ftpRemoteEditToggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:41:44)
    at CommandRegistry.handleCommandEvent (E:/ATOM-portable/Atom/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (E:/ATOM-portable/Atom/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (E:/ATOM-portable/Atom/resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (E:/ATOM-portable/Atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:40.2.0 ftp-remote-edit:toggle (input.hidden-input)
  3x -0:36.1.0 core:backspace (input.hidden-input)
     -0:24.4.0 ftp-remote-edit:toggle (input.hidden-input)
     -0:23 core:confirm (input.hidden-input)
     -0:17.8.0 ftp-remote-edit:toggle (input.hidden-input)
```

**Comment by cschindl** [comment]
Hi @andfra1 ,

the error has already been reported in issue #44 and a solution is being worked on.
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
Can you reproduce the error?
Did you start with a fresh new installaltion of the plugin?
Can you add new servers?
Do you see the tree view when toggle with ctrl + space?

Please answer in issue #44.
