### ISSUE TITLE
Unexpected token � in JSON at position 1

### ISSUE THREAD

**Issue by maxpaynene** [h3imdall/ftp-remote-edit#126]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.5

### Stack Trace

Unexpected token � in JSON at position 1

```
At Unexpected token � in JSON at position 1

SyntaxError: Unexpected token � in JSON at position 1
    at JSON.parse (<anonymous>)
    at /packages/ftp-remote-edit/lib/views/tree-view.js:259:29
    at _TreeView.loadServers (/packages/ftp-remote-edit/lib/views/tree-view.js:295:8)
    at FtpRemoteEdit.toggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:163:25)
    at HTMLElement.ftpRemoteEditToggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:41:44)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

Detail: eyJjb25maWciOnsibG9hZCI6dHJ1ZSwiZGVjcnlwdCI6dHJ1ZSwic3RhcnQiOiI277 9KHgiLCJlbmQiOiJcdTAwMTbvv71FSyJ9LCJwYXNzd29yZCI6eyJleGlzdHMiOnRydWUsImxlbmd0aCI6MTMsImFscGhhbnVtZXJpYyI6dHJ1ZX19
```

### Commands

```
     -1:53.9.0 ftp-remote-edit:toggle (a.)
     -1:49.6.0 core:confirm (input.hidden-input)
  2x -1:30.7.0 ftp-remote-edit:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-clock 0.1.15 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.13 
ftp-remote-edit 0.12.5 
Hydrogen 2.0.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
```

**Comment by cschindl** [comment]
Hi @maxpaynene ,

the error has already been reported in issue #44 and a solution is being worked on.
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
Can you reproduce the error?
Did you start with a fresh new installaltion of the plugin?
Can you add new servers?
Do you see the tree view when toggle with ctrl + space?

Please answer in issue #44.

**Comment by maxpaynene** [comment]
I FIX THIS INSTALL OR STARTING ATOM.APP FROM DESKTOP.

D:
