### ISSUE TITLE
Unexpected token Q in JSON at position 0

### ISSUE THREAD

**Issue by jpcenteno80** [h3imdall/ftp-remote-edit#132]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.5

### Stack Trace

Unexpected token Q in JSON at position 0

```
At Unexpected token Q in JSON at position 0

SyntaxError: Unexpected token Q in JSON at position 0
    at JSON.parse (<anonymous>)
    at /packages/ftp-remote-edit/lib/views/tree-view.js:259:29
    at _TreeView.loadServers (/packages/ftp-remote-edit/lib/views/tree-view.js:295:8)
    at FtpRemoteEdit.toggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:163:25)
    at HTMLElement.ftpRemoteEditToggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:41:44)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

Detail: eyJjb25maWciOnsibG9hZCI6dHJ1ZSwiZGVjcnlwdCI6dHJ1ZSwic3RhcnQiOiJRXHUwMDE377 977 9IiwiZW5kIjoi77 9XHUwMDA0QmgifSwicGFzc3dvcmQiOnsiZXhpc3RzIjp0cnVlLCJsZW5ndGgiOjksImFscGhhbnVtZXJpYyI6dHJ1ZX19
```

### Commands

```
     -0:53.7.0 ftp-remote-edit:toggle (input.hidden-input)
 13x -0:46.8.0 core:backspace (input.hidden-input)
     -0:41.9.0 core:confirm (input.hidden-input)
     -0:27.3.0 ftp-remote-edit:toggle (input.hidden-input)
     -0:20.9.0 ftp-remote-edit:edit-servers (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-one-dark-ui)
     -0:08.3.0 ftp-remote-edit:toggle (div.info)
```

### Non-Core Packages

```
autocomplete-python 1.10.3 
file-icons 2.1.13 
ftp-remote-edit 0.12.5 
merge-conflicts 1.4.5 
pdf-view 0.59.0 
script 3.17.3 
```

**Comment by cschindl** [comment]
Hi @jpcenteno80 ,

the error has already been reported in issue #44 and a solution is being worked on.
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
Can you reproduce the error?
Did you start with a fresh new installaltion of the plugin?
Can you add new servers?
Do you see the tree view when toggle with ctrl + space?
Did you change the master password?
Do you use non alphanumeric letters in your password?
Have you changed your Master Password in the past?
Have you added new servers where you have inserted the access data via Copy+Paste? (You may have added invalid characters that were not filtered out)

Please answer in issue #44.
