### ISSUE TITLE
Unexpected token = in JSON at position 0

### ISSUE THREAD

**Issue by xx3l** [h3imdall/ftp-remote-edit#140]
[Enter steps to reproduce:]

1. Open Atom
2. Start Packages -> ftp-remote-edit ->Toggle
Having an error

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.6

### Stack Trace

Unexpected token = in JSON at position 0

```
At Unexpected token = in JSON at position 0

SyntaxError: Unexpected token = in JSON at position 0
    at JSON.parse (<anonymous>)
    at /packages/ftp-remote-edit/lib/views/tree-view.js:258:29
    at _TreeView.loadServers (/packages/ftp-remote-edit/lib/views/tree-view.js:294:8)
    at FtpRemoteEdit.toggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:163:25)
    at HTMLElement.ftpRemoteEditToggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:41:44)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

Detail: eyJjb25maWciOnsibG9hZCI6dHJ1ZSwiZGVjcnlwdCI6dHJ1ZSwic3RhcnQiOiI9Ne /vcKwIiwiZW5kIjoi77 9Ie /vXcifSwicGFzc3dvcmQiOnsiZXhpc3RzIjp0cnVlLCJsZW5ndGgiOjgsImFscGhhbnVtZXJpYyI6ZmFsc2V9fQ==
```

### Commands

```
     -0:19.5.0 ftp-remote-edit:edit-servers (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:16.9.0 core:confirm (input.hidden-input)
     -0:04.1.0 ftp-remote-edit:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
ftp-remote-edit 0.12.6 
```

**Comment by cschindl** [comment]
Hi @xx3l  ,

the error has already been reported in issue #44 and a solution is being worked on.
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
Can you reproduce the error?
Did you start with a fresh new installaltion of the plugin?
Can you add new servers?
Do you see the tree view when toggle with ctrl + space?
Did you change the master password?
Do you use non alphanumeric letters in your password?
Have you changed your Master Password in the past?
Have you added new servers where you have inserted the access data via Copy+Paste? (You may have added invalid characters that were not filtered out)

Please answer in issue #44.
