### ISSUE TITLE
Failed to load the ftp-remote-edit package: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by rompeldunk** [h3imdall/ftp-remote-edit#144]
Note: Same issue as https://github.com/h3imdall/ftp-remote-edit/issues/145

This problem has come up again in 0.12.7. 

I see its ans issue in https://github.com/h3imdall/ftp-remote-edit/issues/97, but I don't think its related.

`[Enter steps to reproduce:]

1. Copy/paste extracted zip of master into .atom/packages
2. Open Atom.io after installed manually into .atom/packages.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.7

### Stack Trace

Failed to load the ftp-remote-edit package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/ftp-remote-edit-master/lib/views/configuration-view.js:4:72)
    at /packages/ftp-remote-edit-master/lib/views/configuration-view.js:15:39)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:11:31)
    at /packages/ftp-remote-edit-master/lib/ftp-remote-edit.js:533:35)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.22.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:903:35)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:617:16)
    at config.transact (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:530:20)
```

### Commands

```
```

### Non-Core Packages

```
ftp-remote-edit 0.12.7 
```

`

**Comment by rompeldunk** [comment]
Here's an output trying to install it from apm install ftp-remote

`Installing ftp-remote-edit@0.12.5 to C:\Users\Vodo\.atom\packages failed

> coffee-script@1.12.8 postinstall C:\Users\Vodo\AppData\Local\Temp\apm-install-dir-1171030-10028-1dk7xy8.3j714i\node_mo
dules\ftp-remote-edit\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cy
an = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset
 = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"cof
fee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also,
 a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release t
argets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + ".
"); console.warn(""); }'

C:\Users\Vodo\AppData\Local\Temp\apm-install-dir-1171030-10028-1dk7xy8.3j714i
`-- (empty)


npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[eval]:1
'if
^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:357:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Vodo\AppData\Local\Temp\apm-install-dir-1171030-10028-
1dk7xy8.3j714i\package.json'
npm WARN apm-install-dir-1171030-10028-1dk7xy8.3j714i No description
npm WARN apm-install-dir-1171030-10028-1dk7xy8.3j714i No repository field.
npm WARN apm-install-dir-1171030-10028-1dk7xy8.3j714i No README data
npm WARN apm-install-dir-1171030-10028-1dk7xy8.3j714i No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\Vodo\\AppData\\Local\\atom\\app-1.22.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Vodo\\
AppData\\Local\\atom\\app-1.22.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\
Vodo\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Vodo\\.atom\\.apmrc" "install" "C:\\Users\\Vodo\\AppData\\Local\\T
emp\\d-1171030-10028-1mgc62f.oq8joo5hfr\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-styl
e" "--msvs_version=2013"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var r
ed, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yel
low = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Pleas
e update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (
no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" +
 reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cya
n + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coffee-script@1.12.8 postinstall script 'node --eval 'if (require("./package.json").name === "cof
fee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { r
ed = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved
!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescr
ipt\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yello
w + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. L
earn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the coffee-script package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red =
yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[
36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yell
ow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.
warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This ne
w release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" +
 reset + "."); console.warn(""); }'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs coffee-script
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls coffee-script
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Vodo\AppData\Local\Temp\apm-install-dir-1171030-10028-1dk7xy8.3j714i\npm-debug.log
npm ERR! code 1`

**Comment by rompeldunk** [comment]
Redirecting issue in https://github.com/h3imdall/ftp-remote-edit/issues/145
