### ISSUE TITLE
Files don't load after being left for a while

### ISSUE THREAD

**Issue by BWPanda** [h3imdall/ftp-remote-edit#163]
Similar to https://github.com/h3imdall/ftp-remote-edit/issues/107, when I haven't interacted with Atom for a while (5-10 mins), then I try to open a file, the spinning icon appears next to it but it never opens. If I click another file, it may open, but the first never does (spinning icon stays there). If I toggle the parent folder, the spinning icons disappears, but the file still won't open upon clicking it further.

I enabled debug mode for this package and this is what was output (hope it helps):

```
Uncaught (in promise) TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/usr/share/atom/resources/app/node_modules/marked/lib/marked.js:138:12)
    at Function.Lexer.lex (/usr/share/atom/resources/app/node_modules/marked/lib/marked.js:129:22)
    at marked (/usr/share/atom/resources/app/node_modules/marked/lib/marked.js:1219:37)
    at NotificationElement.module.exports.NotificationElement.render (/usr/share/atom/resources/app/node_modules/notifications/lib/notification-element.js:111:39)
    at new NotificationElement (/usr/share/atom/resources/app/node_modules/notifications/lib/notification-element.js:47:39)
    at Object.createView (/usr/share/atom/resources/app/node_modules/notifications/lib/main.js:117:22)
    at ViewRegistry.createView (/usr/share/atom/resources/app/src/view-registry.js:160:57)
    at ViewRegistry.getView (/usr/share/atom/resources/app/src/view-registry.js:127:25)
    at Object.addNotificationView (/usr/share/atom/resources/app/node_modules/notifications/lib/main.js:151:66)
    at /usr/share/atom/resources/app/node_modules/notifications/lib/main.js:39:30
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NotificationManager.addNotification (/usr/share/atom/resources/app/src/notification-manager.js:184:24)
    at NotificationManager.addError (/usr/share/atom/resources/app/src/notification-manager.js:145:23)
    at Connector.showMessage (/home/panda/.atom/packages/ftp-remote-edit/lib/connectors/connector.js:56:26)
    at /home/panda/.atom/packages/ftp-remote-edit/lib/views/file-view.js:314:34
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Please let me know if I can provide further info.

**Comment by BWPanda** [comment]
Ok, here's a better report:

```
/home/panda/.atom/packages/ftp-remote-edit/lib/views/server-view.js:99
connector:downloadFile /[SNIP]/sandbox/modules/views_slideshow_cycle2/views_slideshow_cycle2.info /tmp/ce16899d/[SNIP]/sandbox/modules/views_slideshow_cycle2/views_slideshow_cycle2.info

/home/panda/.atom/packages/ftp-remote-edit/lib/views/server-view.js:102
connector:connect

/home/panda/.atom/packages/ftp-remote-edit/lib/views/server-view.js:102
sftp:get

/home/panda/.atom/packages/ftp-remote-edit/lib/views/server-view.js:102
connector:disconnect

/home/panda/.atom/packages/ftp-remote-edit/lib/views/server-view.js:99
connector:downloadFile /[SNIP]/sandbox/modules/views_slideshow_cycle2/views_slideshow_cycle2.css /tmp/ce16899d/[SNIP]/sandbox/modules/views_slideshow_cycle2/views_slideshow_cycle2.css

/home/panda/.atom/packages/ftp-remote-edit/lib/views/server-view.js:102
connector:connect

/home/panda/.atom/packages/ftp-remote-edit/lib/views/server-view.js:102
sftp:get

/home/panda/.atom/packages/ftp-remote-edit/lib/views/server-view.js:102
sftp:connect:error

2 /home/panda/.atom/packages/ftp-remote-edit/lib/views/server-view.js:102
connector:disconnect

<embedded>:98901 Uncaught (in promise) TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/usr/share/atom/resources/app/node_modules/marked/lib/marked.js:138:12)
    at Function.Lexer.lex (/usr/share/atom/resources/app/node_modules/marked/lib/marked.js:129:22)
    at marked (/usr/share/atom/resources/app/node_modules/marked/lib/marked.js:1219:37)
    at NotificationElement.module.exports.NotificationElement.render (/usr/share/atom/resources/app/node_modules/notifications/lib/notification-element.js:111:39)
    at new NotificationElement (/usr/share/atom/resources/app/node_modules/notifications/lib/notification-element.js:47:39)
    at Object.createView (/usr/share/atom/resources/app/node_modules/notifications/lib/main.js:117:22)
    at ViewRegistry.createView (/usr/share/atom/resources/app/src/view-registry.js:160:57)
    at ViewRegistry.getView (/usr/share/atom/resources/app/src/view-registry.js:127:25)
    at Object.addNotificationView (/usr/share/atom/resources/app/node_modules/notifications/lib/main.js:154:64)
    at /usr/share/atom/resources/app/node_modules/notifications/lib/main.js:39:30
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NotificationManager.addNotification (/usr/share/atom/resources/app/src/notification-manager.js:184:24)
    at NotificationManager.addError (/usr/share/atom/resources/app/src/notification-manager.js:145:23)
    at Connector.showMessage (/home/panda/.atom/packages/ftp-remote-edit/lib/connectors/connector.js:56:26)
    at /home/panda/.atom/packages/ftp-remote-edit/lib/views/file-view.js:314:34
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

When I opened 'views_slideshow_cycle2.info' it opened fine. But then the doorbell rang and I went to answer it. When I came back about 5 mins later and tried to open 'views_slideshow_cycle2.css', it had the problem explained above.

**Comment by cschindl** [comment]
Hi @BWPanda,

the error is caused by another library when the error notification is displayed. So I think a different plugin causes the error. Can you list all plugins used?

**Comment by BWPanda** [comment]
This and https://atom.io/packages/terminal-tab are the only community packages I have in Atom.
