### ISSUE TITLE
Uncaught TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by fgomezserna** [h3imdall/ftp-remote-edit#164]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.9

### Stack Trace

Uncaught TypeError: Cannot read property 'constructor' of undefined

```
At C:\Users\fran\.atom\packages\ftp-remote-edit\lib\ftp-remote-edit.js:409

TypeError: Cannot read property 'constructor' of undefined
    at FtpRemoteEdit.paste (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:409:25)
    at HTMLElement.ftpRemoteEditPaste (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:52:43)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:1399:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.3/resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:40.1.0 editor:newline (input.hidden-input)
     -4:35.8.0 core:save (input.hidden-input)
     -3:47 ftp-remote-edit:copy (span.name.icon.icon-file-text)
     -3:44.4.0 ftp-remote-edit:paste (span.name.icon.icon-file-directory)
  6x -3:29.9.0 core:delete (input.hidden-input)
  2x -2:39.2.0 core:copy (input.hidden-input)
     -1:18.9.0 ftp-remote-edit:rename (span.name.icon.icon-file-text)
  4x -1:17.6.0 core:move-left (input.hidden-input)
  6x -1:16.8.0 core:backspace (input.hidden-input)
     -1:14.7.0 core:confirm (input.hidden-input)
     -0:36.7.0 ftp-remote-edit:new-directory (span.name.icon.icon-file-directory)
     -0:33.7.0 core:confirm (input.hidden-input)
     -0:29.2.0 ftp-remote-edit:new-directory (span.name.icon.icon-file-directory)
     -0:27.5.0 core:confirm (input.hidden-input)
     -0:12.2.0 ftp-remote-edit:copy (span.name.icon.icon-file-text)
     -0:09.3.0 ftp-remote-edit:paste (div.header.list-item)
```

### Non-Core Packages

```
ftp-remote-edit 0.12.9 
```

**Comment by cschindl** [comment]
Hi @fgomezserna,

can you provide some info to try to replicate the error?
