### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, mkdir '~/AppData\Local\Temp\53bf8564\ec2-18-23...

### ISSUE THREAD

**Issue by Wallacel13** [h3imdall/ftp-remote-edit#189]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.12

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, mkdir 'C:\Users\Wallace\AppData\Local\Temp\53bf8564\ec2-18-231-170-37.sa-east-1.compute.amazonaws.com\var\www\ionic\App2\myApp3\src\providers\contacts'

```
At fs.js:895

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Wallace\AppData\Local\Temp\53bf8564\ec2-18-231-170-37.sa-east-1.compute.amazonaws.com\var\www\ionic\App2\myApp3\src\providers\contacts'
    at fs.mkdirSync (fs.js:895:18)
    at Proxy.fs.mkdirSync (ELECTRON_ASAR.js:669:16)
    at /packages/ftp-remote-edit/lib/helper/helper.js:30:18
    at Array.reduce (native)
    at createLocalPath (/packages/ftp-remote-edit/lib/helper/helper.js:27:11)
    at _FileView.open (/packages/ftp-remote-edit/lib/views/file-view.js:222:5)
    at /packages/ftp-remote-edit/lib/views/file-view.js:85:12)
    at HTMLLIElement.dispatch (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLLIElement.elemData.handle (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -9:28.1.0 ftp-remote-edit:edit-servers (atom-pane.pane.active)
     -9:24.7.0 core:confirm (input.hidden-input)
     -9:19.6.0 ftp-remote-edit:toggle (atom-pane.pane.active)
     -8:20.7.0 ftp-remote-edit:new-file (span.name.icon.icon-file-directory)
     -8:15.9.0 core:confirm (input.hidden-input)
  3x -7:09.0 ftp-remote-edit:delete (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
file-icons 2.1.18 
ftp-remote-edit 0.12.12 
```

**Comment by cschindl** [comment]
A similar issue #162 has already been reported by a Mac OS X user. Can you provide some info to try to replicate the error?
