### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/AppData\Local\Temp\8bfa6933\159.65.146.12\v...

### ISSUE THREAD

**Issue by Balaji-Rahunathan** [h3imdall/ftp-remote-edit#192]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.12

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\monisha\AppData\Local\Temp\8bfa6933\159.65.146.12\var\www\html\aqua\models\production'

```
At C:\Users\monisha\.atom\packages\ftp-remote-edit\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\monisha\AppData\Local\Temp\8bfa6933\159.65.146.12\var\www\html\aqua\models\production'
    at fs.mkdirSync (fs.js:895:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:669:16)
    at Function.sync (/packages/ftp-remote-edit/node_modules/mkdirp/index.js:71:13)
    at Proxy.writeFileSync (/packages/ftp-remote-edit/node_modules/fs-plus/lib/fs-plus.js:291:14)
    at _DirectoryView.newFile (/packages/ftp-remote-edit/lib/views/directory-view.js:470:18)
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:319:23)
    at HTMLDivElement.dispatch (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4121:28)
    at Object.trigger (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4350:12)
    at /packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4901:17)
    at Function.each (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:374:23)
    at AddDialog.each (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:139:17)
    at /packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4900:15)
    at /packages/ftp-remote-edit/node_modules/space-pen/lib/space-pen.js:606:19)
    at AddDialog.onConfirm (/packages/ftp-remote-edit/lib/dialogs/add-dialog.js:24:10)
    at HTMLDivElement.coreConfirm (/packages/ftp-remote-edit/lib/dialogs/dialog.js:46:14)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -3:30.4.0 ftp-remote-edit:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:26.4.0 core:confirm (input.hidden-input)
     -3:13 ftp-remote-edit:new-file (div.header.list-item)
  2x -3:10.4.0 core:backspace (input.hidden-input)
     -3:06.5.0 core:confirm (input.hidden-input)
     -0:21.7.0 ftp-remote-edit:new-file (span.name.icon.icon-file-directory)
     -0:18.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.32.2 
autocomplete-modules 2.0.0 
emmet 2.4.3 
file-icons 2.1.18 
ftp-remote-edit 0.12.12 
language-babel 2.84.0 
language-javascript-jsx 0.3.7 
seti-ui 1.10.0 
```

**Comment by cschindl** [comment]
Hi @Balaji-Rahunathan ,

is there possibly already a file with this name or was there already an error when creating the directory before?

**Comment by joerg** [comment]
I am having the same problem from time to time and it is quite simple to reproduce:

1: Create a file
2: Delete the file
3: Create a directory with the same name

The underlying issue is that if you delete a remote file the cached file is not deleted. Of course this also happens if you have a directory and try to create file with the same name.
