### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/AppData\Local\Temp\75e5df9b\192.168.0.12\ak...

### ISSUE THREAD

**Issue by wacki4** [h3imdall/ftp-remote-edit#193]
On sftp connection, created path. In path try to create file which don't exist, got error.

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.12

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Lukasz\AppData\Local\Temp\75e5df9b\192.168.0.12\akredytacje\www\akredytacje-dev\modules\administracja\pages\pliki'

```
At C:\Users\Lukasz\.atom\packages\ftp-remote-edit\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\Lukasz\AppData\Local\Temp\75e5df9b\192.168.0.12\akredytacje\www\akredytacje-dev\modules\administracja\pages\pliki'
    at fs.mkdirSync (fs.js:895:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:669:16)
    at Function.sync (/packages/ftp-remote-edit/node_modules/mkdirp/index.js:71:13)
    at Proxy.writeFileSync (/packages/ftp-remote-edit/node_modules/fs-plus/lib/fs-plus.js:291:14)
    at _DirectoryView.newFile (/packages/ftp-remote-edit/lib/views/directory-view.js:470:18)
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:319:23)
    at HTMLDivElement.dispatch (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4121:28)
    at Object.trigger (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4350:12)
    at /packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4901:17)
    at Function.each (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:374:23)
    at AddDialog.each (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:139:17)
    at /packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4900:15)
    at /packages/ftp-remote-edit/node_modules/space-pen/lib/space-pen.js:606:19)
    at AddDialog.onConfirm (/packages/ftp-remote-edit/lib/dialogs/add-dialog.js:24:10)
    at HTMLDivElement.coreConfirm (/packages/ftp-remote-edit/lib/dialogs/dialog.js:46:14)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -1:21.1.0 core:confirm (input.hidden-input)
     -1:15.7.0 ftp-remote-edit:new-file (span.name.icon.icon-file-directory)
  3x -1:13.2.0 core:backspace (input.hidden-input)
     -1:10.7.0 core:confirm (input.hidden-input)
     -1:03.8.0 ftp-remote-edit:new-file (span.name.icon.icon-file-directory)
 10x -1:01.3.0 core:backspace (input.hidden-input)
     -0:55.8.0 core:confirm (input.hidden-input)
     -0:35.5.0 ftp-remote-edit:new-file (span.name.icon.icon-file-directory)
     -0:32.3.0 core:backspace (input.hidden-input)
     -0:30.6.0 core:confirm (input.hidden-input)
     -0:22.2.0 ftp-remote-edit:delete (span.name.icon.icon-file-directory)
     -0:18 ftp-remote-edit:new-directory (span.name.icon.icon-file-directory)
     -0:16 core:confirm (input.hidden-input)
     -0:13.3.0 ftp-remote-edit:new-file (div.header.list-item)
  4x -0:11.5.0 core:backspace (input.hidden-input)
     -0:07.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
file-icons 2.1.18 
ftp-remote-edit 0.12.12 
highlight-selected 0.13.1 
intentions 1.1.5 
jquery-snippets 11.0.0 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
php-getters-setters 0.5.5 
```

**Comment by cschindl** [comment]
The bug has already been posted in issue #192.
