### ISSUE TITLE
Uncaught TypeError: Cannot create property 'textContent' on string 'Define a password to protect ...

### ISSUE THREAD

**Issue by houd1ni** [h3imdall/ftp-remote-edit#2]
[Enter steps to reproduce:]

1. click this button http://prntscr.com/em5cdj
2. Choose "open a config".
3. Type a password, accept it.
4. get this error: http://prntscr.com/em5ch4

**Atom**: 1.16.0-beta0 ia32
**Electron**: 1.3.13
**OS**: Windows pro 10 latest
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.6.0

### Stack Trace

Uncaught TypeError: Cannot create property 'textContent' on string 'Define a password to protect your connection information.'

```
At C:\Users\Mihail-764\.atom\packages\ftp-remote-edit\lib\ftp-remote-edit-view.js:112

TypeError: Cannot create property 'textContent' on string 'Define a password to protect your connection information.'
    at FtpRemoteEditView.setState (ftp-remote-edit-view.js:112:7)
    at Object.editconfiguration (ftp-remote-edit.js:98:31)
    at atom-workspace.ftp-remote-edit:editconfiguration (ftp-remote-edit.js:48:55)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at HTMLButtonElement.MessageView.configButton.addEventListener.event (message-view.js:22:21)
```

### Commands

```
     -0:22.8.0 ftp-remote-edit:toggle (input.hidden-input)
     -0:21.1.0 ftp-remote-edit:editconfiguration (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:13.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.1 
coffee-compile 0.24.0 
ex-mode 0.14.0 
ftp-remote-edit 0.6.0 
highlight-selected 0.12.0 
linter 2.1.0 
linter-coffeescript 1.0.0 
remote-edit 1.9.0 
remote-edit2 3.0.0 
Remote-FTP 0.10.7 
```

**Comment by cschindl** [comment]
Should be solved in #7. @h3imdall Please check and close this issue.
