### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by bloodndn** [h3imdall/ftp-remote-edit#269]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.3
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/quicksilver/.atom/packages/ftp-remote-edit/lib/views/configuration-view.js:837

TypeError: Cannot read property '0' of undefined
    at ConfigurationView.test (/packages/ftp-remote-edit/lib/views/configuration-view.js:837:34)
    at /packages/ftp-remote-edit/lib/views/configuration-view.js:538:12)
```

### Commands

```
     -9:46.3.0 core:save (input.hidden-input)
  2x -9:41 core:move-right (input.hidden-input)
  3x -9:40.1.0 core:backspace (input.hidden-input)
     -9:35.9.0 core:save (input.hidden-input)
     -9:33 core:backspace (input.hidden-input)
     -9:30.9.0 core:save (input.hidden-input)
     -9:28 core:move-left (input.hidden-input)
     -9:26.8.0 core:backspace (input.hidden-input)
     -9:25.6.0 core:save (input.hidden-input)
     -9:24.2.0 core:backspace (input.hidden-input)
     -9:22.5.0 core:save (input.hidden-input)
     -9:16.5.0 core:move-left (input.hidden-input)
     -9:14.5.0 core:save (input.hidden-input)
     -7:22 ftp-remote-edit:toggle (table.package-keymap-table.table.native-key-bindings.text)
     -6:04.7.0 ftp-remote-edit:edit-servers (atom-workspace.workspace.scrollbars-visible-always.theme-rocket-dark-syntax.theme-atom-dark-ui)
     -5:23.8.0 core:cut (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
ftp-remote-edit 0.14.0 
rocket-dark-syntax 1.0.0 
```

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.14.1](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.14.1)).
