### ISSUE TITLE
Unsyncing after idle

### ISSUE THREAD

**Issue by miles-collier** [h3imdall/ftp-remote-edit#28]
Every time I seem to keep Atom online for a couple hours it seems to stop syncing.

Cannot access files, folders, but shows as if the connection is still active.
After re-connection the existing open files don't sync back up (like Notepad++ does). 
So each time this happens I have to re-open Atom and copy/paste the changes and re-sync the files.

**Comment by cschindl** [comment]
Hi @miles-collier, 

i was able to reproduce the error when using SFTP connections. When using the "keep connection alive" option, the connection was interrupted without attempting to establish a new connection. I added function to checks connection status everytime the "connect" function is called. This hopefully solves the issue. Please try and give us a feedback.

**Comment by miles-collier** [comment]
I am unsure if this would cause the same problem, but to quickly reproduce the issue I disabled and reconnected my internet connection.

After reconnection, same problem but now with this error.
`TypeError: Cannot read property '_stream' of undefined
    at Sftp.isConnected (file:///C:/Users/Icarus/.atom/packages/ftp-remote-edit/lib/connectors/sftp.js:46:28)
    at Connector.connect (file:///C:/Users/Icarus/.atom/packages/ftp-remote-edit/lib/connectors/connector.js:57:20)
    at Connector.existsFile (file:///C:/Users/Icarus/.atom/packages/ftp-remote-edit/lib/connectors/connector.js:314:17)
    at _FileView.open (file:///C:/Users/Icarus/.atom/packages/ftp-remote-edit/lib/views/file-view.js:88:30)
    at space-pen-li.<anonymous> (file:///C:/Users/Icarus/.atom/packages/ftp-remote-edit/lib/views/file-view.js:48:12)
    at space-pen-li.dispatch (C:\Users\Icarus\.atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-li.elemData.handle (C:\Users\Icarus\.atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4121:28`

Unsure if that's because of my test method, I'll keep it open and try to reproduce the exact original issue.

If I relaunch Atom, the existing files also do not resync.

**Comment by cschindl** [comment]
Hi @miles-collier,

i've fixed the bug that caused the above problem. So we must wait until @h3imdall merged the changes. However, the adjustments have only an effect on the already opened folders and files in a session. When closing and opening the editor, all connection information are lost. Saving an open file from previous session does not return to automatic synchronization with the FTP server. This is part of the security concept since after restart all connection information are encrypted and can only be decrypted and used in this session by entering the master password.

**Comment by miles-collier** [comment]
Everything seems good now, thanks guys!
