### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by Monstreur** [h3imdall/ftp-remote-edit#3]
[Enter steps to reproduce:]

1. ...create new file
2. ...rename it

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.6.0

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At C:\Users\Monstreur\.atom\packages\ftp-remote-edit\lib\Ftp.js:167

ReferenceError: path is not defined
    at Object.cb (/packages/ftp-remote-edit/lib/Ftp.js:167:29)
    at /packages/ftp-remote-edit/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/ftp-remote-edit/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/ftp-remote-edit/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
  4x -1:04.4.0 core:move-left (input.hidden-input)
     -1:03.6.0 core:backspace (input.hidden-input)
  3x -0:50.4.0 core:save (input.hidden-input)
     -0:38.6.0 core:copy (input.hidden-input)
     -0:36.2.0 bookmarks:jump-to-next-bookmark (input.hidden-input)
     -0:34.5.0 ftp-remote-edit:rename-file (div.message.icon.icon-file-text.selected)
     -0:33.1.0 core:paste (input.hidden-input)
     -0:30.3.0 core:select-all (input.hidden-input)
     -0:30.1.0 core:cut (input.hidden-input)
     -0:28.3.0 ftp-remote-edit:rename-file (div.message.icon.icon-file-text.selected)
     -0:26.4.0 core:paste (input.hidden-input)
     -0:18 ftp-remote-edit:rename-file (div.message.icon.icon-file-text.selected)
     -0:16.6.0 core:paste (input.hidden-input)
     -0:15.7.0 core:confirm (input.hidden-input)
     -0:02.9.0 ftp-remote-edit:rename-file (div.message.icon.icon-file-text.selected)
     -0:01.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
ftp-remote-edit 0.6.0 
```

**Comment by h3imdall** [comment]
The issue was solved in version 0.8.0
