### ISSUE TITLE
Uncaught TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by henning101** [h3imdall/ftp-remote-edit#305]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.16.3

### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:636

TypeError: path must be a string or Buffer
    at Object.fs.open (fs.js:636:11)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:193:20)
    at Object.fs.writeFile (fs.js:1281:6)
    at /packages/ftp-remote-edit/node_modules/fs-plus/lib/fs-plus.js:300:21
    at /packages/remote-atom/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:153:5)
```

### Commands

```
     -4:46 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:24.9.0 atom-terminal-panel:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:12.9.0 atom-terminal-panel:toggle-autocompletion (div.panel.atp-panel.panel-bottom)
     -4:12.8.0 editor:select-line (div.panel.atp-panel.panel-bottom)
     -1:49.9.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -1:49.7.0 core:select-all (input.autocomplete.autocomplete-input.autocomplete-text)
     -1:47.4.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -1:47.3.0 core:select-all (input.hidden-input)
     -1:46.8.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -1:46.7.0 core:select-all (input.hidden-input)
     -1:46.4.0 core:backspace (input.hidden-input)
     -0:39.3.0 remote-ssh:start (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:32.5.0 remote-ssh:create-config (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:17.8.0 remote-ssh:toggle-search (atom-pane.pane.active)
     -0:10.4.0 remote-ssh:start (atom-pane.pane.active)
```

### Non-Core Packages

```
ftp-remote-edit 0.16.3 
Remote-SSH 0.11.0 
```

**Comment by cschindl** [comment]
Hi @henning101,

according to the protocol the error seems to be thrown by another plugin (remote-atom, remote-ssh). Try to disable the "Remote-SSH" plugin and check if the bug has been fixed.
