### ISSUE TITLE
Uncaught TypeError: FindDialog is not a constructor

### ISSUE THREAD

**Issue by marshallburns** [h3imdall/ftp-remote-edit#319]
[Enter steps to reproduce:]

1. Create a server and open it to display the initial directory
2. Right click on server and choose find remote path

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.17.1

### Stack Trace

Uncaught TypeError: FindDialog is not a constructor

```
At /Users/mb166v/.atom/packages/ftp-remote-edit/lib/ftp-remote-edit.js:1793

TypeError: FindDialog is not a constructor
    at FtpRemoteEdit.findRemotePath (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:1793:20)
    at HTMLElement.ftpRemoteEditFindRemotePath (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:78:54)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348736)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347211)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:717275)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725281)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -6:14.6.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -6:14.2.0 core:paste (input.hidden-input)
     -6:12.3.0 core:save (input.hidden-input)
     -3:27.5.0 settings-view:open (div.tool-panel.tree-view)
     -2:59 core:backspace (input.hidden-input)
  3x -2:58.5.0 core:move-left (input.hidden-input)
  3x -2:14.9.0 ftp-remote-edit:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -1:40.5.0 ftp-remote-edit:edit-servers (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
 18x -1:33.5.0 core:select-left (input.hidden-input)
     -1:19.9.0 core:move-right (input.hidden-input)
  2x -1:19.5.0 core:select-right (input.hidden-input)
     -0:49.8.0 core:paste (input.hidden-input)
     -0:37.4.0 core:backspace (input.hidden-input)
     -0:07.8.0 ftp-remote-edit:find-remote-path (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
ftp-remote-edit 0.17.1 
pretty-json 2.1.2 
```

**Comment by cschindl** [comment]
Fixed in release [0.17.2](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.17.2). Thanks for the hint.
