### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasPassword' of null

### ISSUE THREAD

**Issue by obaaa8** [h3imdall/ftp-remote-edit#341]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 ia32
**Electron**: 1.7.11
**OS**: Ubuntu 18.04.2
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.17.4

### Stack Trace

Uncaught TypeError: Cannot read property 'hasPassword' of null

```
At /home/hiba/.atom/packages/ftp-remote-edit/lib/ftp-remote-edit.js:452

TypeError: Cannot read property 'hasPassword' of null
    at FtpRemoteEdit.toggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:452:17)
    at HTMLElement.ftpRemoteEditToggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:56:44)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/opt/atom/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/opt/atom/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -1:36.6.0 ftp-remote-edit:toggle (div.tool-panel.tree-view)
```

### Non-Core Packages

```
column-select 1.0.1 
ftp-remote-edit 0.17.4 
invert-selection 1.0.0 
language-blade 0.43.1 
language-liquidsoap 1.2.0 
language-vue 0.25.0 
laravel 0.7.1 
multiline-select 1.8.2 
overscroll 0.1.0 
platformio-ide-terminal 2.9.4 
scroll-through-time 0.3.1 
Stylus 3.2.0 
vue-autocomplete 0.1.1 
```

**Comment by cschindl** [comment]
Please update to the newest version 1.40.1 and try again.

**Comment by eliamarsu** [comment]
I solved removing atom and installing it from CLI with apt: https://linuxize.com/post/how-to-install-atom-text-editor-on-ubuntu-20-04/#installing-atom-with-apt
