### ISSUE TITLE
Uncaught TypeError: Electron.remote.dialog.showSaveDialog(...).then is not a function

### ISSUE THREAD

**Issue by LahiruChamal** [h3imdall/ftp-remote-edit#427]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.7
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.18.2

### Stack Trace

Uncaught TypeError: Electron.remote.dialog.showSaveDialog(...).then is not a function

```
At /Users/lahiruchamal/.atom/packages/ftp-remote-edit/lib/ftp-remote-edit.js:1383

TypeError: Electron.remote.dialog.showSaveDialog(...).then is not a function
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:1383:101
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:1393:12
    at FtpRemoteEdit.download (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:1394:8)
    at HTMLElement.ftpRemoteEditDownload (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:82:46)
    at CommandRegistry.handleCommandEvent (/private/var/folders/55/27lp7c4d2y5fv67ppg8wz4nm0000gn/T/AppTranslocation/757CA015-26A0-4F47-9ECE-156A2FDB38C7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:349786)
    at CommandRegistry.dispatch (/private/var/folders/55/27lp7c4d2y5fv67ppg8wz4nm0000gn/T/AppTranslocation/757CA015-26A0-4F47-9ECE-156A2FDB38C7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:348261)
    at AtomEnvironment.dispatchContextMenuCommand (/private/var/folders/55/27lp7c4d2y5fv67ppg8wz4nm0000gn/T/AppTranslocation/757CA015-26A0-4F47-9ECE-156A2FDB38C7/d/Atom.app/Contents/Resources/app/static/<embedded>:1:726039)
    at EventEmitter.t (/private/var/folders/55/27lp7c4d2y5fv67ppg8wz4nm0000gn/T/AppTranslocation/757CA015-26A0-4F47-9ECE-156A2FDB38C7/d/Atom.app/Contents/Resources/app/static/<embedded>:1:734045)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -2:05.3.0 editor:toggle-line-comments (atom-pane.pane.active)
  2x -1:58.4.0 ftp-remote-edit:toggle (atom-pane.pane.active)
     -1:52.2.0 core:confirm (input.hidden-input)
     -1:41.2.0 ftp-remote-edit:download (span.name.icon.icon-file-directory)
     -1:16.3.0 ftp-remote-edit:duplicate (span.name.icon.icon-file-text)
     -1:14.4.0 core:confirm (input.hidden-input)
  4x -1:06.3.0 ftp-remote-edit:chmod (span.name.icon.icon-file-text)
     -0:29.6.0 ftp-remote-edit:download (div.header.list-item)
  2x -0:21.6.0 ftp-remote-edit:chmod (span.name.icon.icon-file-directory)
     -0:03.9.0 ftp-remote-edit:download (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
ftp-remote-edit 0.18.2 
```

**Comment by lokeshm** [comment]
Facing same issue...
Any solution?
