### ISSUE TITLE
Uncaught ReferenceError: tmp is not defined

### ISSUE THREAD

**Issue by nocturnalguru** [h3imdall/ftp-remote-edit#450]
upgraded to ftp-remote-edit 

The above was automatically generated when I used the 'copy' button to report the issue.  Not sure if this is something in pulsar that still needs to be updated.

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.102.0 x64
**Electron**: 12.2.3
**OS**: Ubuntu 22.04.2
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.20.0

### Stack Trace

Uncaught ReferenceError: tmp is not defined

```
At /home/pjiggy/.pulsar/packages/ftp-remote-edit/lib/views/tree-view.js:612

ReferenceError: tmp is not defined
    at TreeView.remoteKeyboardNavigationDown (tree-view.js:612:10)
    at TreeView.remoteKeyboardNavigation (tree-view.js:556:14)
    at HTMLDivElement.<anonymous> (tree-view.js:126:38)
    at HTMLDivElement.dispatch (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:12.4.0 ftp-remote-edit:toggle (div.tool-panel.tree-view)
     -1:10.1.0 core:confirm (input.hidden-input)
 10x -1:00.7.0 core:move-down (div.ftp-remote-edit-view.ftp-remote-edit-resizer.tool-panel)
```

### Non-Core Packages

```
ftp-remote-edit 0.20.0 
```

### Additional Information

simply entering the password and selecting the server will trigger the error as soon as I navigate using the arrow keys to expand the directory tree.

Love the work you have done so far...

**Comment by vitneum** [comment]
tree-view.js
[ tmp = current; ]
edit to [ let tmp = current; ]
