### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by lnvglr** [h3imdall/ftp-remote-edit#46]
1. Open file via FTP
2. Save
3. (It saves the file successfully but throws an error)

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: 'atom-ftp-editor' package vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/<user_name>/.atom/packages/atom-ftp-editor/lib/main.js:115

TypeError: Cannot read property 'path' of undefined
    at Object.__uploadCurrent (/packages/atom-ftp-editor/lib/main.js:115:84)
    at HTMLDocument.__onsave (/packages/atom-ftp-editor/lib/main.js:95:21)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -6:31.8.0 core:save (input.hidden-input)
     -6:06.1.0 autocomplete-plus:confirm (input.hidden-input)
     -6:06.1.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -6:05.4.0 autocomplete-plus:confirm (input.hidden-input)
     -6:04.5.0 core:select-all (input.hidden-input)
     -6:03.7.0 core:save (input.hidden-input)
     -5:26.6.0 core:backspace (input.hidden-input)
     -5:24.9.0 core:save (input.hidden-input)
     -5:18.4.0 editor:newline (input.hidden-input)
     -5:17.3.0 autocomplete-plus:confirm (input.hidden-input)
     -5:17.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -5:14.4.0 core:save (input.hidden-input)
     -5:13.6.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -4:50.8.0 core:save (input.hidden-input)
     -4:32.2.0 settings-view:open (input.hidden-input)
     -0:01.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
ftp-remote-edit 0.11.7 
```

**Comment by cschindl** [comment]
Hi @lnvglr ,

i can not reproduce the error. Please activate the debug mode and write the output here purely. The debug mode can be activated as follows:

Open the atom "config" (File -> config)
Search for "ftp-remote-edit"
Add the line as a sub-dot: "debug: true"
The config should then look something like this:

"Ftp-remote-edit":
     Config: "54baad1 ....."
     Password: "78b2 ... 622"
     Debug: true

Save and restart the Atom editor
Toogle Delevoper Tools (Ctrl + Shift + i) and open the "Console"
Then please try to save a file and post the output here.

**Comment by lnvglr** [comment]
Hey @cschindl,
very briefly after having had the issue it disappeared, so really I can't reproduce the error anymore either. Thank you so much, though!
