### ISSUE TITLE
Uncaught SyntaxError: Unexpected token � in JSON at position 0

### ISSUE THREAD

**Issue by seba2305** [h3imdall/ftp-remote-edit#47]
[Enter steps to reproduce:]

1.  already added a server operating normally
2. Then press "Edit servers", appears the field to add the password for the session
3. I type the password (use lower case letters and numbers)

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.11.7

### Stack Trace

Uncaught SyntaxError: Unexpected token � in JSON at position 0

```
At file:///C:/Users/**{USERNAME}**/AppData/Local/atom/app-1.18.0/resources/app/static/index.html:1

SyntaxError: Unexpected token � in JSON at position 0
    at Object.parse (native)
    at ConfigurationView.loadConfig (/packages/ftp-remote-edit/lib/views/configuration-view.js:415:26)
    at ConfigurationView.reload (/packages/ftp-remote-edit/lib/views/configuration-view.js:455:31)
    at FtpRemoteEdit.editServers (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:182:28)
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:39:50)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -8:37.9.0 core:delete (input.hidden-input)
     -8:36.6.0 core:paste (input.hidden-input)
     -8:35.4.0 core:undo (input.hidden-input)
  2x -8:22.4.0 core:paste (input.hidden-input)
     -7:41.6.0 ftp-remote-edit:edit-servers (atom-pane.pane)
     -7:40.5.0 core:confirm (input.hidden-input)
     -7:18.9.0 window:toggle-dev-tools (atom-pane.pane)
     -7:00.7.0 ftp-remote-edit:edit-servers (span.name.icon.icon-file-symlink-directory.icon-file-directory)
     -6:59.4.0 core:confirm (input.hidden-input)
     -6:29.9.0 ftp-remote-edit:edit-servers (span.name.icon.icon-file-symlink-directory.icon-file-directory)
     -6:28.8.0 core:confirm (input.hidden-input)
     -6:15.4.0 ftp-remote-edit:edit-servers (div.header.list-item.project-root-header)
     -6:14.2.0 core:confirm (input.hidden-input)
     -1:40.7.0 ftp-remote-edit:edit-servers (ol.ftp-remote-edit-list.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:34.6.0 core:confirm (input.hidden-input)
     -1:30.8.0 ftp-remote-edit:edit-servers (ol.ftp-remote-edit-list.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.8 
ftp-remote-edit 0.11.7 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-php 1.3.2 
linter-ui-default 1.6.2 
minimap 4.28.2 
php-hyperclick 1.2.1 
w3c-validation 0.4.0 
```

**Comment by cschindl** [comment]
@seba2305  The error has already been reported in issue #44 and a solution is being worked on.

**Comment by Sofianio** [comment]
I have the same problem,
I have 2 windows opened, the first one works fine but in the second one when I ctrl+space I get this exception.
I wanted to have 2 sessions, one for each window
