### ISSUE TITLE
Uncaught SyntaxError: Unexpected token . in JSON at position 0

### ISSUE THREAD

**Issue by igun997** [h3imdall/ftp-remote-edit#52]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.11.8

### Stack Trace

Uncaught SyntaxError: Unexpected token . in JSON at position 0

```
At file:///C:/Users/SystemFive/AppData/Local/atom/app-1.18.0/resources/app/static/index.html:1

SyntaxError: Unexpected token . in JSON at position 0
    at Object.parse (native)
    at _TreeView.loadServers (/packages/ftp-remote-edit/lib/views/tree-view.js:116:27)
    at FtpRemoteEdit.toggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:152:21)
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:38:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:09.4.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:04.8.0 ftp-remote-edit:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:01.9.0 core:confirm (input.hidden-input)
     -0:48.6.0 ftp-remote-edit:toggle (atom-pane.pane.active)
     -0:26.7.0 ftp-remote-edit:edit-servers (atom-pane.pane.active)
```

### Non-Core Packages

```
ftp-remote-edit 0.11.8 
http-post 1.0.1 
Remote-FTP 1.1.2 
```

**Comment by cschindl** [comment]
@igun997 The error has already been reported in issue #44  and a solution is being worked on.
