### ISSUE TITLE
Uncaught SyntaxError: Unexpected token y in JSON at position 0

### ISSUE THREAD

**Issue by uraikus** [h3imdall/ftp-remote-edit#67]
The module was working fine the other night. Now all of a sudden, issues...

1. toggles->Asks to create temporary password.
2. ->Edit Servers ->creates error:

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.11.8

### Stack Trace

Uncaught SyntaxError: Unexpected token y in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html:1

SyntaxError: Unexpected token y in JSON at position 0
    at Object.parse (native)
    at ConfigurationView.loadConfig (/packages/ftp-remote-edit/lib/views/configuration-view.js:415:26)
    at ConfigurationView.reload (/packages/ftp-remote-edit/lib/views/configuration-view.js:455:31)
    at FtpRemoteEdit.editServers (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:182:28)
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:39:50)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:43.8.0 ftp-remote-edit:toggle (div.tool-panel.tree-view)
     -0:40.3.0 core:confirm (input.hidden-input)
     -0:34.7.0 ftp-remote-edit:edit-servers (div.tool-panel.tree-view)
```

### Non-Core Packages

```
color-picker 2.2.5 
ftp-remote-edit 0.11.8 
```

**Comment by cschindl** [comment]
@uraikus The error has already been reported in issue #44 and a solution is being worked on.
