### ISSUE TITLE
Uncaught SyntaxError: Unexpected token J in JSON at position 0

### ISSUE THREAD

**Issue by yyynnn** [h3imdall/ftp-remote-edit#73]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.11.11

### Stack Trace

Uncaught SyntaxError: Unexpected token J in JSON at position 0

```
At file:///C:/Users/SNikolaev/AppData/Local/atom/app-1.18.0/resources/app/static/index.html:1

SyntaxError: Unexpected token J in JSON at position 0
    at Object.parse (native)
    at _TreeView.loadServers (/packages/ftp-remote-edit/lib/views/tree-view.js:117:27)
    at FtpRemoteEdit.toggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:152:21)
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:38:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at /packages/title-bar-replacer/lib/title-bar-replacer.js:429:27)
    at HTMLDivElement.dispatch (/packages/title-bar-replacer/node_modules/jquery/dist/jquery.js:4737:27)
    at HTMLDivElement.elemData.handle (/packages/title-bar-replacer/node_modules/jquery/dist/jquery.js:4549:28)
```

### Commands

```
     -0:31.9.0 ftp-remote-edit:toggle (atom-text-editor.editor)
     -0:24.8.0 core:confirm (input.hidden-input)
     -0:16.1.0 ftp-remote-edit:toggle (atom-text-editor.editor)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-live-server 2.1.2 
atom-wrap-in-tag 0.6.0 
auto-detect-indentation 1.3.0 
autoclose 0.0.2 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
autoprefixer 3.7.1 
busy-signal 1.4.3 
css-spy 0.6.0 
double-tag 0.9.0 
duotone-berries-syntax 0.1.1 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
duotone-darkpool-syntax 1.1.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
expose 0.14.0 
file-icons 2.1.9 
ftp-remote-edit 0.11.11 
git-plus 7.9.3 
git-time-machine 1.5.9 
gutter-shadow 1.1.0 
highlight-selected 0.13.1 
html-to-css 0.2.2 
indent-guide-improved 1.4.12 
intentions 1.1.5 
language-babel 2.68.0 
language-javascript-jsx 0.3.7 
language-postcss 1.3.1 
language-pug 0.0.21 
linter 2.2.0 
linter-pug 1.3.1 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-autohide 0.10.1 
minimap-cursorline 0.2.0 
new-era-syntax 1.1.0 
newton-dark-syntax 1.1.7 
newton-dark-ui 1.1.2 
paraiso-dark 2.0.2 
pigments 0.39.1 
prettier-atom 0.37.0 
pristine-ui 1.1.6 
pure-syntax 0.3.0 
red-wavy-underline 0.3.3 
rest-client 1.3.1 
sass-autocompile 0.13.3 
split-diff 1.4.3 
tag 0.5.0 
title-bar-replacer 1.2.0 
tool-bar-basic 2.0.1 
tree-view-copy-relative-path 1.2.0 
uglify 1.3.1 
vaporwave-syntax 0.0.6 
vaporwave-ui 0.0.2 
webbox-color 0.5.9 
Wild-Cherry 0.9.0 
wingyplus-syntax 0.5.1 
wingyplus-ui 0.1.1 
```

**Comment by cschindl** [comment]
@yyynnn The error has already been reported in issue #44 and a solution is being worked on. 
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
