### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by vkamelin** [h3imdall/ftp-remote-edit#86]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.11.11

### Stack Trace

Uncaught SyntaxError: Unexpected token < in JSON at position 0

```
At file:///usr/share/atom/resources/app/static/index.html:1

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at ConfigurationView.loadConfig (/packages/ftp-remote-edit/lib/views/configuration-view.js:416:26)
    at ConfigurationView.reload (/packages/ftp-remote-edit/lib/views/configuration-view.js:456:31)
    at FtpRemoteEdit.editServers (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:182:28)
    at HTMLElement.ftpRemoteEditEditServers (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:39:50)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:13.3.0 ftp-remote-edit:edit-servers (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:09.7.0 core:confirm (input.hidden-input)
     -0:03.1.0 ftp-remote-edit:edit-servers (atom-pane.pane.active)
```

### Non-Core Packages

```
autocomplete-php 0.3.7 
ftp-remote-edit 0.11.11 
language-volt 0.2.2 
```

**Comment by vkamelin** [comment]
I'm getting this when I'm trying to edit servers first time.

**Comment by cschindl** [comment]
@vkamelin The error has already been reported in issue #44 and a solution is being worked on.
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
Can you reproduce  the error? 
Did you start with a fresh new installaltion of the plugin?
Can you add new servers?
Do you see the tree view when toggle with ctrl + space?

**Comment by cschindl** [comment]
@vkamelin  Please answer in issue #44
