### ISSUE TITLE
Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by 72428** [h3imdall/ftp-remote-edit#91]
TypeError: Cannot read property 'file' of undefined
    at Object.__getCurrentFile (/Users/robbert/.atom/packages/atom-ftp-editor/lib/main.js:122:60)
    at Object.__uploadCurrent (/Users/robbert/.atom/packages/atom-ftp-editor/lib/main.js:113:35)
    at atom-workspace.currentUpload (/Users/robbert/.atom/packages/atom-ftp-editor/lib/main.js:70:21)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

This happends when i try to upload to my server, i can delete everything off the server using the plugin but uploading throws me this error.

**Comment by cschindl** [comment]
Hi @72428,

the error is caused by the plugin "atom-ftp-editor". Here we can only provide support for the "Ftp-Remote-Edit" plugin. Please contact the author of the "atom-ftp-editor" plugin.
