### ISSUE TITLE
Uncaught SyntaxError: Unexpected token s in JSON at position 0

### ISSUE THREAD

**Issue by OSCAR-WOS** [h3imdall/ftp-remote-edit#93]
[Enter steps to reproduce:]

1. No clue how to reproduce. I was connected to one server with SSH protocol, and then switched to another using SSH by password.

**Atom**: 1.20.0-beta3 x64
**Electron**: 1.6.9
**OS**: Debian GNU/Linux
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.11.11

### Stack Trace

Uncaught SyntaxError: Unexpected token s in JSON at position 0

```
At file:///usr/share/atom-beta/resources/app/static/index.html:1

SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)
    at _TreeView.loadServers (/packages/ftp-remote-edit/lib/views/tree-view.js:117:27)
    at FtpRemoteEdit.toggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:152:21)
    at HTMLElement.ftpRemoteEditToggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:38:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom-beta/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom-beta/resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/usr/share/atom-beta/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:44.8.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -1:42.4.0 ftp-remote-edit:toggle (atom-pane.pane)
     -1:40.2.0 core:confirm (input.hidden-input)
     -1:35.5.0 ftp-remote-edit:edit-servers (atom-pane.pane)
  2x -1:28.3.0 ftp-remote-edit:toggle (atom-pane.pane)
     -0:56.7.0 core:confirm (input.hidden-input)
     -0:06.1.0 ftp-remote-edit:toggle (input#ftp-remote-edit.showOnRightSide.input-checkbox)
```

### Non-Core Packages

```
busy-signal 1.4.3 
ftp-remote-edit 0.11.11 
intentions 1.1.5 
language-sourcepawn 0.7.2 
linter 2.2.0 
linter-js-standard 4.0.0 
linter-ui-default 1.6.8 
```

**Comment by cschindl** [comment]
Hi @OSCAR-WOS, 

the error has already been reported in issue #44 and a solution is being worked on.
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
Can you reproduce the error?
Did you start with a fresh new installaltion of the plugin?
Can you add new servers?
Do you see the tree view when toggle with ctrl + space?

**Comment by cschindl** [comment]
@OSCAR-WOS Please answer in issue #44
